/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.io.ParseException;
import com.vividsolutions.jts.io.WKTReader;
import javax.swing.JOptionPane;
/**
 *
 * @author Murillo
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        txtGeomA = new javax.swing.JTextField();
        txtGeomB = new javax.swing.JTextField();
        lblGeomA = new javax.swing.JLabel();
        lblGeomB = new javax.swing.JLabel();
        lblOverlaps = new javax.swing.JLabel();
        lblContains = new javax.swing.JLabel();
        lblWhitin = new javax.swing.JLabel();
        lblCrosses = new javax.swing.JLabel();
        lblTouches = new javax.swing.JLabel();
        lblIntersects = new javax.swing.JLabel();
        lblDisjoint = new javax.swing.JLabel();
        lblIntersectsResult = new javax.swing.JLabel();
        lblDisjointResult = new javax.swing.JLabel();
        lblTouchResult = new javax.swing.JLabel();
        lblCrossesResult = new javax.swing.JLabel();
        lblWithinResult = new javax.swing.JLabel();
        lblContainsResult = new javax.swing.JLabel();
        lblOverlapsResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtGeomA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeomAActionPerformed(evt);
            }
        });

        lblGeomA.setText("Geometria A");

        lblGeomB.setText("Geometria B");

        lblOverlaps.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOverlaps.setText("A Overlaps B:");

        lblContains.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContains.setText("A Contains B:");

        lblWhitin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWhitin.setText("A Whitin B:");

        lblCrosses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCrosses.setText("A Crosses B:");

        lblTouches.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTouches.setText("A Touch B:");

        lblIntersects.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIntersects.setText("A Intersects B:");

        lblDisjoint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisjoint.setText("A Disjoint B:");

        lblIntersectsResult.setText("-");

        lblDisjointResult.setText("-");

        lblTouchResult.setText("-");

        lblCrossesResult.setText("-");

        lblWithinResult.setText("-");

        lblContainsResult.setText("-");

        lblOverlapsResult.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeomA)
                            .addComponent(lblGeomB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeomA)
                            .addComponent(txtGeomB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOverlaps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOverlapsResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContains)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContainsResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWhitin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWithinResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCrosses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCrossesResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDisjoint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDisjointResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIntersects)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIntersectsResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTouches)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTouchResult)))
                        .addGap(0, 348, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcular)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblContains, lblCrosses, lblDisjoint, lblIntersects, lblOverlaps, lblTouches, lblWhitin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeomA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeomA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeomB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeomB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisjoint)
                    .addComponent(lblDisjointResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntersects)
                    .addComponent(lblIntersectsResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTouches)
                    .addComponent(lblTouchResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrosses)
                    .addComponent(lblCrossesResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWhitin)
                    .addComponent(lblWithinResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContains)
                    .addComponent(lblContainsResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOverlaps)
                    .addComponent(lblOverlapsResult))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        WKTReader wtk = new WKTReader();
        Geometry geomA = null;
        Geometry geomB = null;

        try {
            geomA = wtk.read(txtGeomA.getText());
            geomB = wtk.read(txtGeomB.getText());
        } catch (ParseException ex) {
             JOptionPane.showMessageDialog(null, "Digite os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        if (geomA != null && geomB != null) {
            lblDisjointResult.setText(Boolean.toString(geomA.disjoint(geomB)));
            lblIntersectsResult.setText(Boolean.toString(geomA.intersects(geomB)));
            lblTouchResult.setText(Boolean.toString(geomA.touches(geomB)));
            lblCrossesResult.setText(Boolean.toString(geomA.crosses(geomB)));
            lblWithinResult.setText(Boolean.toString(geomA.within(geomB)));
            lblContainsResult.setText(Boolean.toString(geomA.contains(geomB)));
            lblOverlapsResult.setText(Boolean.toString(geomA.overlaps(geomB)));
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtGeomAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeomAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeomAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblContains;
    private javax.swing.JLabel lblContainsResult;
    private javax.swing.JLabel lblCrosses;
    private javax.swing.JLabel lblCrossesResult;
    private javax.swing.JLabel lblDisjoint;
    private javax.swing.JLabel lblDisjointResult;
    private javax.swing.JLabel lblGeomA;
    private javax.swing.JLabel lblGeomB;
    private javax.swing.JLabel lblIntersects;
    private javax.swing.JLabel lblIntersectsResult;
    private javax.swing.JLabel lblOverlaps;
    private javax.swing.JLabel lblOverlapsResult;
    private javax.swing.JLabel lblTouchResult;
    private javax.swing.JLabel lblTouches;
    private javax.swing.JLabel lblWhitin;
    private javax.swing.JLabel lblWithinResult;
    private javax.swing.JTextField txtGeomA;
    private javax.swing.JTextField txtGeomB;
    // End of variables declaration//GEN-END:variables
}
